apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: lab-kuber
spec:
  template:
    spec:
      containers:
        - name: bff
          image: mablinov2704/bff:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: lab-kuber
spec:
  template:
    spec:
      containers:
        - name: user-service
          image: mablinov2704/user-service:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: lab-kuber
spec:
  template:
    spec:
      containers:
        - name: message-service
          image: mablinov2704/message-service:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lab-kuber
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: mablinov2704/frontend:latest