apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <team-namespace>
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pg-pvc.yaml
  - postgres.yaml
  - migrate-users.yaml
  - migrate-messages.yaml
  - users-service.yaml
  - messages-service.yaml
  - bff.yaml
  - frontend.yaml
  - ingress.yaml
  - pg-service.yaml