apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: lab-kuber
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_safe_password"
  USER_DB_DSN: "host=postgres user=postgres password=postgres_safe_password dbname=messanger_db_users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=postgres password=postgres_safe_password dbname=messanger_db_messages sslmode=disable"